version: '3.8'

services:
  prod:
    container_name: prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production
    env_file: .env.production
  
