# build environment
FROM node:15.3.0-alpine3.10 as build-stage
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
COPY . ./

RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
COPY  nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]